parameters:
  - name: FORCE_DEPLOY
    default: false
    description: "Forcibly deploy the docker image made by this build to production"
    type: boolean

pull_requests:
  - master

pushes:
  - master
  - ableton_utils_test
